---
title: "License"
output:
  workflowr::wflow_html:
    toc: false
---

This notebook is licensed under a Creative Commons Attribution 4.0 International License, which permits use, sharing, adaptation, distribution and reproduction in any medium or format, as long as you give appropriate credit to the original author(s) and the source, provide a link to the Creative Commons license, and indicate if changes were made. The images or other third party material in this notebook are included in the notebook’s Creative Commons license, unless indicated otherwise in a credit line to the material. If material is not included in the notebook’s Creative Commons license and your intended use is not permitted by statutory regulation or exceeds the permitted use, you will need to obtain permission directly from the copyright holder. To view a copy of this license, visit http://creativecommons.org/licenses/by/4.0/.

If you use any results from this notebook, please explicitly acknowledge that
the results are retrieved from https://doi.org/10.5281/zenodo.1473807,
and cite the following article:

> Xiang Zhu and Matthew Stephens (2018).
> Large-scale genome-wide enrichment analyses identify new
> trait-associated genes and pathways across 31 human phenotypes.
> *Nature Communications* 9, 4361. <https://doi.org/10.1038/s41467-018-06805-x>.

The source code in the notebook is licensed under the [GNU General Public License, version 3.0 (GPLv3)][code-license].

Icons in this notebook are directly linked from the Noun Project <https://thenounproject.com>.

[code-license]: https://www.gnu.org/licenses/gpl-3.0.txt
